### ISSUE TITLE
JNR issue at 93bc0bc97abb76d4930b97dccec40de9faef68f5 (Current HEAD)

### ISSUE THREAD

**Issue by 11xor6** [airlift/airship#23]
First provisioned a coordinator; which worked correctly:

```
$ ./airship environment provision-aws --coordinator-config \
> com.example.config:airship-coordinator:1 \
> --instance-type t1.micro --security-group sec-group --ami ami-3e41d257 --key-pair airship-test \
> --repository http://example.com:8082/nexus/content/groups/public/ staging
Waiting for access key to register with AWS......done!
```

Second tried to provision some agents:

```
$ ./airship agent provision --agent-config @com.example.config:agent-aws-t1.micro:1 \
> --instance-type t1.micro --security-group sec-group --ami ami-3e41d257 \
> --key-pair airship-test --count 3
```

And get this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: jnr/ffi/Struct
    at jnr.posix.POSIXFactory.<clinit>(POSIXFactory.java:12)
    at io.airlift.airship.cli.POSIXFactory.getPOSIX(POSIXFactory.java:22)
    at io.airlift.airship.cli.Ansi.<clinit>(Ansi.java:15)
    at io.airlift.airship.cli.SimpleRecord$Builder.addValue(SimpleRecord.java:56)
    at io.airlift.airship.cli.TablePrinter.<init>(TablePrinter.java:40)
    at io.airlift.airship.cli.TablePrinter.<init>(TablePrinter.java:28)
    at io.airlift.airship.cli.TableOutputFormat.displayAgents(TableOutputFormat.java:52)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.displayAgents(Airship.java:332)
    at io.airlift.airship.cli.Airship$AgentProvisionCommand.execute(Airship.java:866)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:274)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:218)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:177)
    at io.airlift.airship.cli.Airship.main(Airship.java:151)
Caused by: java.lang.ClassNotFoundException: jnr.ffi.Struct
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 13 more
```

The machines do start, but it is impossible to do anything with them:

```
$ ./airship agent
Exception in thread "main" java.lang.NoClassDefFoundError: jnr/ffi/Struct
    at jnr.posix.POSIXFactory.<clinit>(POSIXFactory.java:12)
    at io.airlift.airship.cli.POSIXFactory.getPOSIX(POSIXFactory.java:22)
    at io.airlift.airship.cli.Ansi.<clinit>(Ansi.java:15)
    at io.airlift.airship.cli.SimpleRecord$Builder.addValue(SimpleRecord.java:56)
    at io.airlift.airship.cli.TablePrinter.<init>(TablePrinter.java:40)
    at io.airlift.airship.cli.TablePrinter.<init>(TablePrinter.java:28)
    at io.airlift.airship.cli.TableOutputFormat.displayAgents(TableOutputFormat.java:52)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.displayAgents(Airship.java:332)
    at io.airlift.airship.cli.Airship$AgentShowCommand.execute(Airship.java:819)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:274)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:218)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:177)
    at io.airlift.airship.cli.Airship.main(Airship.java:151)
Caused by: java.lang.ClassNotFoundException: jnr.ffi.Struct
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
```

**Comment by electrum** [comment]
Thanks! Fixed in #26
