### ISSUE TITLE
"coordinator ssh" doesn't work

### ISSUE THREAD

**Issue by 11xor6** [airlift/airship#35]
$ airship --debug coordinator ssh
2013-06-11T12:25:32.703-0700     INFO   main    io.airlift.log.Logging  Logging to stderr
Exception in thread "main" UnexpectedResponseException{request=Request{uri=http://ec2-23-22-68-45.compute-1.amazonaws.com:64000/v1/admin/coordinator, method=GET, headers={}, bodyGenerator=null}, statusCode=500, statusMessage=Cannot compute unique prefix size for collection with duplicate entries, headers={Content-Length=[1411], Content-Type=[text/html;charset=ISO-8859-1], Cache-Control=[must-revalidate,no-cache,no-store]}}
    at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:75)
    at io.airlift.http.client.ApacheHttpClient$1.handleResponse(ApacheHttpClient.java:134)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
    at io.airlift.http.client.ApacheHttpClient.execute(ApacheHttpClient.java:122)
    at io.airlift.airship.cli.HttpCommander.sshCoordinator(HttpCommander.java:268)
    at io.airlift.airship.cli.Airship$CoordinatorSshCommand.execute(Airship.java:818)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:276)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:220)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:179)
    at io.airlift.airship.cli.Airship.main(Airship.java:153)

**Comment by dain** [comment]
Does "coordinator show" work for you?

**Comment by 11xor6** [comment]
No, same error I believe

**Comment by 11xor6** [comment]
$ airship --debug coordinator show
2013-06-11T15:53:34.337-0700     INFO   main    io.airlift.log.Logging  Logging to stderr
Exception in thread "main" UnexpectedResponseException{request=Request{uri=http://ec2-23-22-68-45.compute-1.amazonaws.com:64000/v1/admin/coordinator, method=GET, headers={}, bodyGenerator=null}, statusCode=500, statusMessage=Cannot compute unique prefix size for collection with duplicate entries, headers={Content-Length=[1411], Content-Type=[text/html;charset=ISO-8859-1], Cache-Control=[must-revalidate,no-cache,no-store]}}
    at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:75)
    at io.airlift.http.client.ApacheHttpClient$1.handleResponse(ApacheHttpClient.java:134)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
    at io.airlift.http.client.ApacheHttpClient.execute(ApacheHttpClient.java:122)
    at io.airlift.airship.cli.HttpCommander.showCoordinators(HttpCommander.java:189)
    at io.airlift.airship.cli.Airship$CoordinatorShowCommand.execute(Airship.java:720)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:276)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:220)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:179)
    at io.airlift.airship.cli.Airship.main(Airship.java:153)

**Comment by dain** [comment]
Oh this is an error in the provisioner/coordinator... it is getting duplicates in the list of coordinators for some reason.

**Comment by 11xor6** [comment]
I dug into the code and apparently a coordinator keeps a list of "other coordinators," but the coordinator also somehow adds itself to that list causing duplicates to be returned by io.airlift.airship.coordinator.Coordinator.getCoordinators().

I don't have time to finish trying to fix this issue, but this is a report of what is actually going wrong.
