### ISSUE TITLE
NPE on install with uuid filter

### ISSUE THREAD

**Issue by electrum** [airlift/airship#5]
Command:

```
# airship --debug install -u f9cc discovery-server:1.4 @discovery:1-SNAPSHOT
2012-11-19T18:45:58.173-0800     INFO   main    io.airlift.log.Logging  Logging to stderr
Exception in thread "main" java.lang.RuntimeException: Server Error
    at io.airlift.airship.cli.HttpCommander.showAgents(HttpCommander.java:282)
    at io.airlift.airship.cli.Airship$InstallCommand.execute(Airship.java:437)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:270)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:214)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:173)
    at io.airlift.airship.cli.Airship.main(Airship.java:147)
```

Launcher log:

```
2012-11-19T18:45:58.774-0800     WARN   http-worker-85  org.eclipse.jetty.servlet.ServletHandler        /v1/admin/agent
java.lang.NullPointerException: null
        at io.airlift.airship.coordinator.StringFunctions$1.apply(StringFunctions.java:20) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.StringFunctions$1.apply(StringFunctions.java:17) ~[main.jar:0.9-SNAPSHOT]
        at com.google.common.base.Predicates$CompositionPredicate.apply(Predicates.java:534) ~[guava-12.0.jar:na]
        at com.google.common.collect.Iterators$8.computeNext(Iterators.java:688) ~[guava-12.0.jar:na]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-12.0.jar:na]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-12.0.jar:na]
        at com.google.common.collect.Iterators.size(Iterators.java:191) ~[guava-12.0.jar:na]
        at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:228) ~[guava-12.0.jar:na]
        at io.airlift.airship.coordinator.AgentFilterBuilder$UuidPredicate.<init>(AgentFilterBuilder.java:273) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder$1.apply(AgentFilterBuilder.java:160) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder$1.apply(AgentFilterBuilder.java:156) ~[main.jar:0.9-SNAPSHOT]
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:491) ~[guava-12.0.jar:na]
        at java.util.AbstractList$Itr.next(AbstractList.java:358) ~[na:1.7.0_06]
        at com.google.common.base.Predicates.defensiveCopy(Predicates.java:619) ~[guava-12.0.jar:na]
        at com.google.common.base.Predicates.or(Predicates.java:146) ~[guava-12.0.jar:na]
        at io.airlift.airship.coordinator.AgentFilterBuilder.build(AgentFilterBuilder.java:155) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder.build(AgentFilterBuilder.java:94) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AdminResource.getAllAgents(AdminResource.java:78) ~[main.jar:0.9-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_06]
        at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_06]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708) ~[jersey-server-1.9.1.jar:1.9.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1365) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.airship.coordinator.auth.AuthFilter.doFilter(AuthFilter.java:70) ~[main.jar:0.9-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.http.server.GZipRequestFilter.doFilter(GZipRequestFilter.java:49) ~[http-server-0.66.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77) ~[jetty-servlets-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:181) ~[jetty-servlets-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:50) ~[http-server-0.66.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483) [jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412) [jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:121) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.Server.handle(Server.java:351) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection.messageComplete(AbstractHttpConnection.java:909) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.messageComplete(AbstractHttpConnection.java:966) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:897) [jetty-http-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-http-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609) [jetty-io-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45) [jetty-io-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599) [jetty-util-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534) [jetty-util-8.1.1.v20120215.jar:8.1.1.v20120215]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_06]
```

**Comment by electrum** [comment]
Similar error if I install with a host filter. It prompts, I say yes, then errors:

```
# airship --debug install -h x.x.x.x discovery-server:1.4 @discovery:1-SNAPSHOT
2012-11-19T18:48:39.167-0800     INFO   main    io.airlift.log.Logging  Logging to stderr
uuid  host           machine                               status  type     location
f9cc  x.x.x.x  yyyy  ONLINE  unknown  /elided

Are you sure you would like to INSTALL on these agents? [Y/n] y

Exception in thread "main" UnexpectedResponseException{request=Request{uri=http://localhost:28888/v1/slot?limit=1&uuid=f9cc9b42-2c81-496a-8ea6-7e64e11fc596, method=POST, headers={x-airship-slots-version=[862d980e6ee1161c76b0dbe7e15ffb9a], Content-Type=[application/json]}, bodyGenerator=io.airlift.http.client.JsonBodyGenerator@59b66caf}, statusCode=500, statusMessage='Server Error', headers={Content-Length=[1280], Content-Type=[text/html;charset=ISO-8859-1], Cache-Control=[must-revalidate,no-cache,no-store]}}
    at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:72)
    at io.airlift.http.client.ApacheHttpClient$1.handleResponse(ApacheHttpClient.java:125)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1085)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1059)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1050)
    at io.airlift.http.client.ApacheHttpClient.execute(ApacheHttpClient.java:113)
    at io.airlift.airship.cli.HttpCommander.install(HttpCommander.java:92)
    at io.airlift.airship.cli.Airship$InstallCommand.execute(Airship.java:467)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:270)
    at io.airlift.airship.cli.Airship$AirshipCommanderCommand.execute(Airship.java:214)
    at io.airlift.airship.cli.Airship$AirshipCommand.call(Airship.java:173)
    at io.airlift.airship.cli.Airship.main(Airship.java:147)
```

Launcher log:

```
2012-11-19T18:49:34.492-0800     WARN   http-worker-89  org.eclipse.jetty.servlet.ServletHandler        /v1/slot
java.lang.NullPointerException: null
        at io.airlift.airship.coordinator.StringFunctions$1.apply(StringFunctions.java:20) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.StringFunctions$1.apply(StringFunctions.java:17) ~[main.jar:0.9-SNAPSHOT]
        at com.google.common.base.Predicates$CompositionPredicate.apply(Predicates.java:534) ~[guava-12.0.jar:na]
        at com.google.common.collect.Iterators$8.computeNext(Iterators.java:688) ~[guava-12.0.jar:na]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-12.0.jar:na]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-12.0.jar:na]
        at com.google.common.collect.Iterators.size(Iterators.java:191) ~[guava-12.0.jar:na]
        at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:228) ~[guava-12.0.jar:na]
        at io.airlift.airship.coordinator.AgentFilterBuilder$UuidPredicate.<init>(AgentFilterBuilder.java:273) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder$1.apply(AgentFilterBuilder.java:160) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder$1.apply(AgentFilterBuilder.java:156) ~[main.jar:0.9-SNAPSHOT]
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:491) ~[guava-12.0.jar:na]
        at java.util.AbstractList$Itr.next(AbstractList.java:358) ~[na:1.7.0_06]
        at com.google.common.base.Predicates.defensiveCopy(Predicates.java:619) ~[guava-12.0.jar:na]
        at com.google.common.base.Predicates.or(Predicates.java:146) ~[guava-12.0.jar:na]
        at io.airlift.airship.coordinator.AgentFilterBuilder.build(AgentFilterBuilder.java:155) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.AgentFilterBuilder.build(AgentFilterBuilder.java:94) ~[main.jar:0.9-SNAPSHOT]
        at io.airlift.airship.coordinator.CoordinatorSlotResource.install(CoordinatorSlotResource.java:101) ~[main.jar:0.9-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_06]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_06]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_06]
        at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_06]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.1.jar:1.9.1]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708) ~[jersey-server-1.9.1.jar:1.9.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1365) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.airship.coordinator.auth.AuthFilter.doFilter(AuthFilter.java:70) ~[main.jar:0.9-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.http.server.GZipRequestFilter.doFilter(GZipRequestFilter.java:49) ~[http-server-0.66.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77) ~[jetty-servlets-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:181) ~[jetty-servlets-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:50) ~[http-server-0.66.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) ~[jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483) [jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412) [jetty-servlet-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:121) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.Server.handle(Server.java:351) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:952) [jetty-http-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-http-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76) [jetty-server-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609) [jetty-io-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45) [jetty-io-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599) [jetty-util-8.1.1.v20120215.jar:8.1.1.v20120215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534) [jetty-util-8.1.1.v20120215.jar:8.1.1.v20120215]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_06]
```

**Comment by dain** [comment]
Add something like this `Predicate<String> startsWithPrefix = compose(and(notNull(), startsWith(shortId.toLowerCase())), toLowerCase());
` to AgentFilter.UUIDPredocate.  Also add some tests with null agent UUIDs to TestAgentFilterBuilder.
